/**
 * Frozen "Add from YouTube link" copy (Design handoff §7).
 * Use these constants everywhere — do not scatter string literals.
 */

export const YOUTUBE_COPY = Object.freeze({
  entry: 'Add from YouTube',
  entryShort: 'YouTube',
  title: 'Add from YouTube',
  helper: 'Single videos only. Audio is saved privately to your library.',
  fieldLabel: 'YouTube link',
  placeholder: 'Paste a YouTube link',
  paste: 'Paste',
  pasteFull: 'Paste from clipboard',
  formats:
    'Works with youtube.com/watch, youtu.be, music.youtube.com and Shorts links. Up to 15 minutes.',
  submit: 'Add to library',
  cancel: 'Cancel',
  valid: 'Looks like a single video.',
  listIgnored: 'Looks like a single video. The playlist part is ignored.',
  detected: 'Title and cover appear in Imports once we fetch them.',
  detectedVideo: 'Video',
  detectedShort: 'Short',
  clipDenied: 'Can’t read your clipboard. Long-press the field and choose Paste.',
  clearLink: 'Clear link',
  errInvalid: 'That doesn’t look like a YouTube video link.',
  errPlaylist: 'Playlists aren’t supported. Paste a link to a single video.',
  errDuplicateTrack: 'Already in your library.',
  openTrack: 'Open track',
  errDuplicateImport: 'Already importing this video.',
  seeImports: 'See Imports',
  errQuota: 'Storage full. Delete tracks or ask for more space.',
  errTooMany: '2 imports are already running. Wait for one to finish.',
  errRate: (n) => `Import limit reached. Try again in ${n} min.`,
  errGeneric: 'Couldn’t start the import. Try again.',
  offline: 'You’re offline. Connect to add from YouTube.',
  offlineToast: 'You’re offline',
  imports: Object.freeze({
    title: 'Imports',
    meta: 'You can leave this page. We’ll keep going.',
    metaShort: 'Keeps going if you leave',
  }),
  waitingMeta: 'Waiting for metadata',
  noCancel: 'Can’t cancel while downloading',
  status: Object.freeze({
    queued: 'Queued',
    downloading: 'Downloading',
    processing: 'Processing',
    ready: 'Ready',
    failed: 'Failed',
    blocked: 'Blocked by YouTube',
    blockedShort: 'Blocked',
  }),
  retry: 'Retry',
  dismiss: 'Dismiss',
  retryLabel: (title) => `Retry import of ${title}`,
  dismissLabel: (title) => `Dismiss import of ${title}`,
  reason: Object.freeze({
    private: 'This video is private.',
    ageRestricted: 'Age-restricted videos can’t be added.',
    live: 'Live streams and premieres can’t be added. Try after it ends.',
    tooLong: 'Longer than 15 minutes. Only shorter videos can be added.',
    tooLarge: 'File is over 50 MB.',
    unavailable: 'This video isn’t available.',
    quota: 'Storage full. Delete tracks or ask for more space.',
    blocked: 'YouTube blocked the server. Try again later.',
    timeout: 'Took too long to import. Try again.',
    interrupted: 'Import was interrupted. Try again.',
    invalidUrl: 'That doesn’t look like a YouTube video link.',
    playlist: 'Playlists aren’t supported.',
    unknown: 'Something went wrong. Try again.',
  }),
  blockedAdminLink: 'Check YouTube settings',
  toastQueued: 'Import started. We’ll add it to your library.',
  toastReady: (title) => `Added ${title}`,
  toastReadyMany: (n) => `Added ${n} tracks`,
  toastPlay: 'Play',
  toastFailed: (title) => `Couldn’t add ${title}. See Imports.`,
  toastDismissFail: 'Couldn’t dismiss. Try again.',
  sourceTag: 'YouTube',
  newPill: 'NEW',
  emptyTitle: 'Your library is empty',
  emptyBody: 'Upload audio or add a song from a YouTube link.',
  emptyUpload: 'Upload',
})

export const ADMIN_YOUTUBE_COPY = Object.freeze({
  tab: 'YouTube',
  pageSub: 'Cookies, yt-dlp and everyone’s imports',
  cookiesTitle: 'YouTube cookies',
  cookiesBody:
    'Only needed if YouTube blocks the server. Upload a Netscape-format cookies.txt. It’s stored encrypted and never shown again.',
  cookiesSet: 'Set',
  cookiesNotSet: 'Not set',
  upload: 'Upload cookies.txt',
  replace: 'Replace cookies.txt',
  replaceHint: 'Replaces any existing file',
  cookiesStale:
    'If imports stay blocked after uploading, the cookies may have expired. Export a fresh file and upload again.',
  cookiesSaved: 'Cookies saved',
  cookiesFail: 'Couldn’t save cookies. Check the file and try again.',
  ytdlpTitle: 'yt-dlp',
  version: 'Installed version',
  cookiesRow: 'Cookies',
  updateRow: 'Update',
  updateHint: 'Via deploy (pinned in engine image)',
  refresh: 'Refresh status',
  statusFail: 'Couldn’t load status',
  importsTitle: 'Imports',
  importsSub: 'all users',
  filter: Object.freeze({ all: 'All', active: 'Active', failed: 'Failed' }),
  columns: Object.freeze({
    user: 'User',
    video: 'Video',
    status: 'Status',
    reason: 'Reason',
    created: 'Created',
    actions: 'Actions',
  }),
  attempts: (n) => `${n} attempts`,
  errorDetail: 'error_detail (admin only)',
  showDetail: 'Show error detail',
  deleteLabel: 'Delete import',
  deleteTitle: 'Delete this import?',
  deleteBody: (email) =>
    `Removes the import for ${email}. If it finished, their track and file are deleted too.`,
  deleteConfirm: 'Delete',
  deleted: 'Import deleted',
  deleteFail: 'Couldn’t delete this import. Try again.',
  empty: 'No imports yet',
  listFail: 'Couldn’t load imports',
})

/** Engine reason_code → copy key (§7 map); anything else falls back to `unknown`. */
const REASON_KEYS = Object.freeze({
  private: 'private',
  age_restricted: 'ageRestricted',
  live: 'live',
  too_long: 'tooLong',
  too_large: 'tooLarge',
  unavailable: 'unavailable',
  quota_exceeded: 'quota',
  blocked_by_youtube: 'blocked',
  timeout: 'timeout',
  interrupted: 'interrupted',
  invalid_url: 'invalidUrl',
  playlist_not_supported: 'playlist',
})

/** @param {string|null|undefined} code */
export function importReasonText(code) {
  return YOUTUBE_COPY.reason[REASON_KEYS[code] || 'unknown']
}
